version: '2'
services:
  mysql:
    image: 'mysql'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  laravel:
    build: .
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql

